"""
Builds the bundled BondED campus-knowledge FAQ index.

Same non-generative TF-IDF + cosine-similarity retrieval approach as
general_knowledge/build_index.py, but for a small, school-specific FAQ set
that ships inside the app as an offline fallback. At runtime the chatbot
prefers the live Firestore `campusFaq` collection (staff-editable) and falls
back to this bundled index when Firestore is unavailable.

Rows in campus_faq.csv whose answer starts with "TODO:" are placeholders for
the school to fill in — they are skipped here so the assistant never speaks
an unfilled template answer. Fill the answer in and rebuild.

Rebuild from the project root:

    python chatbot_training/campus_knowledge/build_campus_index.py
"""
from pathlib import Path
import json

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# Unlike general_knowledge/build_index.py, this FAQ set is small (dozens of
# entries) and every entry asks about a *different action or object*, so there
# is no "Who was Pope in WWII" vs "When did WWII end" collision to protect
# against. Keeping "what/how/is/do" here backfires instead: in a tiny corpus
# the "what is" / "how do i" template bigrams get a high IDF and a bare
# "what is X" query matches whichever FAQ happens to start "what is ...".
# So we use the full English stop-word list and let the content words
# (report, flair, anonymous, poll, server, ...) carry the match.
STOP_WORDS = "english"

BASE = Path(__file__).parent
PROJECT_ROOT = BASE.parents[1]

INPUT_FILE = BASE / "campus_faq.csv"
OUTPUT_FILE = BASE / "campus_knowledge_index.json"
REPORT_FILE = BASE / "evaluation_report.json"
TS_OUTPUT_FILE = PROJECT_ROOT / "utils" / "campusKnowledgeIndex.ts"

TODO_PREFIX = "todo:"

df = pd.read_csv(INPUT_FILE)
df["question"] = df["question"].fillna("").astype(str).str.strip()
df["answer"] = df["answer"].fillna("").astype(str).str.strip()

before = len(df)
df = df[
    (df["question"].str.len() > 0)
    & (df["answer"].str.len() > 0)
    & (~df["answer"].str.lower().str.startswith(TODO_PREFIX))
].drop_duplicates(subset=["question"])
skipped = before - len(df)

questions = df["question"].tolist()
answers = df["answer"].tolist()

if not questions:
    raise SystemExit("campus_faq.csv has no answerable rows (all blank or TODO).")

print(f"Loading {len(questions)} campus FAQ entries ({skipped} TODO/blank skipped)...")

vectorizer = TfidfVectorizer(
    lowercase=True,
    ngram_range=(1, 2),
    stop_words=STOP_WORDS,
    sublinear_tf=True,
    norm="l2",
)

matrix = vectorizer.fit_transform(questions)

vocabulary = {str(word): int(index) for word, index in vectorizer.vocabulary_.items()}
idf = [float(value) for value in vectorizer.idf_]

vectors = []
for row_number in range(matrix.shape[0]):
    row = matrix.getrow(row_number)
    vectors.append({
        "indices": [int(index) for index in row.indices],
        "values": [float(value) for value in row.data],
    })

stop_words = sorted(str(word) for word in (vectorizer.get_stop_words() or []))

knowledge = {
    "metadata": {
        "name": "BondED Campus Knowledge",
        "algorithm": "TF-IDF + Cosine Similarity Retrieval",
        "generative": False,
        "questionCount": int(len(questions)),
        "vocabularySize": int(len(vocabulary)),
        "ngramRange": [1, 2],
    },
    "questions": questions,
    "answers": answers,
    "vocabulary": vocabulary,
    "idf": idf,
    "stopWords": stop_words,
    "vectors": vectors,
}

with OUTPUT_FILE.open("w", encoding="utf-8") as file:
    json.dump(knowledge, file, ensure_ascii=False, separators=(",", ":"))

# Explicit wide type annotation, same reasoning as the other generated index
# files: keeps the TS type-checker cheap and nothing downstream needs literal
# narrowing.
TS_TYPE_DECLARATION = (
    "type CampusKnowledgeIndexShape = {\n"
    "  metadata: {\n"
    "    name: string;\n"
    "    algorithm: string;\n"
    "    generative: boolean;\n"
    "    questionCount: number;\n"
    "    vocabularySize: number;\n"
    "    ngramRange: number[];\n"
    "  };\n"
    "  questions: string[];\n"
    "  answers: string[];\n"
    "  vocabulary: Record<string, number>;\n"
    "  idf: number[];\n"
    "  stopWords: string[];\n"
    "  vectors: { indices: number[]; values: number[] }[];\n"
    "};\n\n"
)

typescript_source = (
    "// AUTO-GENERATED by chatbot_training/campus_knowledge/build_campus_index.py\n"
    "// Non-generative offline FAQ fallback. Do not hand-edit; rebuild it with Python.\n"
    "// Live edits happen in the Firestore `campusFaq` collection at runtime.\n\n"
    + TS_TYPE_DECLARATION
    + "export const CAMPUS_KNOWLEDGE_INDEX: CampusKnowledgeIndexShape = "
    + json.dumps(knowledge, ensure_ascii=False, separators=(",", ":"))
    + ";\n"
)

TS_OUTPUT_FILE.write_text(typescript_source, encoding="utf-8")

report = {
    "faq_entries": int(len(questions)),
    "todo_or_blank_skipped": int(skipped),
    "vocabulary_size": int(len(vocabulary)),
    "matrix_rows": int(matrix.shape[0]),
    "matrix_columns": int(matrix.shape[1]),
    "algorithm": "TF-IDF Retrieval",
    "similarity": "Cosine Similarity",
    "generative_ai": False,
    "typescript_export": str(TS_OUTPUT_FILE),
}
with REPORT_FILE.open("w", encoding="utf-8") as file:
    json.dump(report, file, indent=2)

print("BondED Campus Knowledge index built.")
print("Entries:", len(questions), "| Vocabulary:", len(vocabulary), "| Matrix:", matrix.shape)
print("Created:", OUTPUT_FILE)
print("Created:", TS_OUTPUT_FILE)
