// Generated by scripts/brand/build-brand-assets.py — don't edit by hand;
// run the script with another --logo / --icon to change colourway.
export const BRAND_COLOURWAY = {
  logo: "campus",
  icon: "maroon",
  /** The "ED" of the wordmark, matched to the logo. */
  wordmarkAccent: "#e0a53d",
} as const;
