import { CAMPUS_KNOWLEDGE_INDEX } from "./campusKnowledgeIndex";

/**
 * Non-generative campus FAQ retrieval (TF-IDF + cosine similarity).
 *
 * Two sources, checked in this order:
 *   1. Live Firestore `campusFaq` entries passed in by the caller — staff can
 *      add/edit these in the app, so they take precedence.
 *   2. The bundled offline index generated by
 *      chatbot_training/campus_knowledge/build_campus_index.py.
 *
 * Nothing is generated. An answer is either a stored FAQ answer or null.
 */

export type CampusFaqEntry = { question: string; answer: string };

export type CampusKnowledgeMatch = {
  answer: string;
  matchedQuestion: string;
  similarity: number;
  source: "live" | "bundled";
};

const MIN_SIMILARITY = 0.3;
const MIN_MARGIN = 0.04;

const bundledVocabulary = new Map<string, number>(
  Object.entries(CAMPUS_KNOWLEDGE_INDEX.vocabulary).map(([term, index]) => [
    term,
    Number(index),
  ]),
);
const bundledStopWords = new Set<string>(CAMPUS_KNOWLEDGE_INDEX.stopWords);

const normalizeCampusText = (value: string) =>
  value
    .normalize("NFKD")
    .toLowerCase()
    .replace(/@(?:ai|bondedai)\b/g, " ")
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();

const tokenize = (value: string, stopWords: Set<string>) => {
  const raw = normalizeCampusText(value).match(/\b[a-z0-9]+\b/g) || [];
  return raw.filter((token) => !stopWords.has(token));
};

const withBigrams = (tokens: string[]) => {
  const terms = [...tokens];
  for (let i = 0; i < tokens.length - 1; i += 1) {
    terms.push(`${tokens[i]} ${tokens[i + 1]}`);
  }
  return terms;
};

// Generic question / filler words that carry no topic signal. A match must
// share at least one *content* word beyond these, otherwise a bare
// "what is the weather" can ride the "what is" overlap into an unrelated FAQ.
const GENERIC_WORDS = new Set([
  "what", "how", "why", "when", "where", "who", "which", "is", "are", "am",
  "do", "does", "did", "can", "could", "should", "would", "will", "the", "a",
  "an", "my", "me", "i", "you", "your", "to", "of", "in", "on", "for", "it",
  "this", "that", "and", "or", "with", "about", "get", "got", "there", "any",
]);

const contentWords = (value: string) =>
  new Set(
    tokenize(value, bundledStopWords).filter(
      (token) => token.length >= 3 && !GENERIC_WORDS.has(token),
    ),
  );

const sharesContentWord = (query: string, matchedQuestion: string) => {
  const q = contentWords(query);
  if (q.size === 0) return true; // nothing to check against — let similarity decide
  for (const word of contentWords(matchedQuestion)) {
    if (q.has(word)) return true;
  }
  return false;
};

// ---------------------------------------------------------------------------
// Bundled index search (precomputed vectors)
// ---------------------------------------------------------------------------

const vectorizeAgainstBundled = (input: string) => {
  const terms = withBigrams(tokenize(input, bundledStopWords));
  const counts = new Map<number, number>();
  for (const term of terms) {
    const index = bundledVocabulary.get(term);
    if (index == null) continue;
    counts.set(index, (counts.get(index) || 0) + 1);
  }
  if (counts.size === 0) return new Map<number, number>();

  const weighted = new Map<number, number>();
  let squaredNorm = 0;
  for (const [index, count] of counts) {
    const tf = 1 + Math.log(count);
    const value = tf * Number(CAMPUS_KNOWLEDGE_INDEX.idf[index] || 0);
    weighted.set(index, value);
    squaredNorm += value * value;
  }
  const norm = Math.sqrt(squaredNorm) || 1;
  for (const [index, value] of weighted) weighted.set(index, value / norm);
  return weighted;
};

const sparseDot = (
  query: Map<number, number>,
  indices: readonly number[],
  values: readonly number[],
) => {
  let score = 0;
  for (let i = 0; i < indices.length; i += 1) {
    const q = query.get(Number(indices[i]));
    if (q != null) score += q * Number(values[i] || 0);
  }
  return score;
};

const searchBundled = (input: string): CampusKnowledgeMatch | null => {
  const query = vectorizeAgainstBundled(input);
  if (query.size === 0) return null;

  let bestIndex = -1;
  let best = 0;
  let second = 0;
  for (let i = 0; i < CAMPUS_KNOWLEDGE_INDEX.vectors.length; i += 1) {
    const candidate = CAMPUS_KNOWLEDGE_INDEX.vectors[i];
    const similarity = sparseDot(query, candidate.indices, candidate.values);
    if (similarity > best) {
      second = best;
      best = similarity;
      bestIndex = i;
    } else if (similarity > second) {
      second = similarity;
    }
  }

  if (bestIndex < 0 || best < MIN_SIMILARITY) return null;
  if (best < 0.5 && best - second < MIN_MARGIN) return null;

  const matchedQuestion = String(
    CAMPUS_KNOWLEDGE_INDEX.questions[bestIndex] || "",
  ).trim();
  if (!sharesContentWord(input, matchedQuestion)) return null;

  return {
    answer: String(CAMPUS_KNOWLEDGE_INDEX.answers[bestIndex] || "").trim(),
    matchedQuestion,
    similarity: best,
    source: "bundled",
  };
};

// ---------------------------------------------------------------------------
// Live Firestore entries search (TF-IDF computed at request time)
// ---------------------------------------------------------------------------

const searchEntries = (
  input: string,
  entries: CampusFaqEntry[],
): CampusKnowledgeMatch | null => {
  const cleaned = entries
    .map((entry) => ({
      question: String(entry?.question || "").trim(),
      answer: String(entry?.answer || "").trim(),
    }))
    .filter(
      (entry) =>
        entry.question.length > 0 &&
        entry.answer.length > 0 &&
        !entry.answer.toLowerCase().startsWith("todo:"),
    );
  if (cleaned.length === 0) return null;

  const docTerms = cleaned.map((entry) => withBigrams(tokenize(entry.question, bundledStopWords)));

  // Document frequency across the live set.
  const df = new Map<string, number>();
  for (const terms of docTerms) {
    for (const term of new Set(terms)) df.set(term, (df.get(term) || 0) + 1);
  }
  const n = cleaned.length;
  const idf = (term: string) => Math.log((n + 1) / ((df.get(term) || 0) + 1)) + 1;

  const toVector = (terms: string[]) => {
    const counts = new Map<string, number>();
    for (const term of terms) counts.set(term, (counts.get(term) || 0) + 1);
    const weighted = new Map<string, number>();
    let squaredNorm = 0;
    for (const [term, count] of counts) {
      const value = (1 + Math.log(count)) * idf(term);
      weighted.set(term, value);
      squaredNorm += value * value;
    }
    const norm = Math.sqrt(squaredNorm) || 1;
    for (const [term, value] of weighted) weighted.set(term, value / norm);
    return weighted;
  };

  const queryVector = toVector(withBigrams(tokenize(input, bundledStopWords)));
  if (queryVector.size === 0) return null;

  let bestIndex = -1;
  let best = 0;
  let second = 0;
  for (let i = 0; i < docTerms.length; i += 1) {
    const docVector = toVector(docTerms[i]);
    let similarity = 0;
    for (const [term, q] of queryVector) {
      const d = docVector.get(term);
      if (d != null) similarity += q * d;
    }
    if (similarity > best) {
      second = best;
      best = similarity;
      bestIndex = i;
    } else if (similarity > second) {
      second = similarity;
    }
  }

  if (bestIndex < 0 || best < MIN_SIMILARITY) return null;
  if (best < 0.5 && best - second < MIN_MARGIN) return null;
  if (!sharesContentWord(input, cleaned[bestIndex].question)) return null;

  return {
    answer: cleaned[bestIndex].answer,
    matchedQuestion: cleaned[bestIndex].question,
    similarity: best,
    source: "live",
  };
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Look up a campus FAQ answer. Live Firestore entries (if any) are checked
 * first and win; the bundled offline index is the fallback.
 */
export const retrieveCampusKnowledge = (
  input: string,
  liveEntries: CampusFaqEntry[] = [],
): CampusKnowledgeMatch | null => {
  if (liveEntries.length > 0) {
    const liveMatch = searchEntries(input, liveEntries);
    if (liveMatch) return liveMatch;
  }
  return searchBundled(input);
};

export const getCampusKnowledgeDiagnostics = () => ({
  name: CAMPUS_KNOWLEDGE_INDEX.metadata.name,
  algorithm: CAMPUS_KNOWLEDGE_INDEX.metadata.algorithm,
  generative: CAMPUS_KNOWLEDGE_INDEX.metadata.generative,
  bundledEntries: CAMPUS_KNOWLEDGE_INDEX.metadata.questionCount,
  minimumSimilarity: MIN_SIMILARITY,
});
