from pathlib import Path
import json
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

BASE = Path(__file__).parent
PROJECT_ROOT = BASE.parents[1]

INPUT_FILE = BASE / "general_knowledge.csv"
OUTPUT_FILE = BASE / "knowledge_index.json"
REPORT_FILE = BASE / "evaluation_report.json"
TS_OUTPUT_FILE = PROJECT_ROOT / "utils" / "generalKnowledgeIndex.ts"

df = pd.read_csv(INPUT_FILE)

df["question"] = df["question"].fillna("").astype(str).str.strip()
df["answer"] = df["answer"].fillna("").astype(str).str.strip()

df = df[
    (df["question"].str.len() > 0)
    & (df["answer"].str.len() > 0)
].drop_duplicates(subset=["question", "answer"])

questions = df["question"].tolist()
answers = df["answer"].tolist()

print(f"Loading {len(questions)} general-knowledge entries...")

vectorizer = TfidfVectorizer(
    lowercase=True,
    ngram_range=(1, 2),
    stop_words="english",
    max_features=20000,
    sublinear_tf=True,
    norm="l2",
)

matrix = vectorizer.fit_transform(questions)

print("TF-IDF model built.")
print("Matrix shape:", matrix.shape)

vocabulary = {
    str(word): int(index)
    for word, index in vectorizer.vocabulary_.items()
}

idf = [float(value) for value in vectorizer.idf_]

vectors = []
for row_number in range(matrix.shape[0]):
    row = matrix.getrow(row_number)
    vectors.append({
        "indices": [int(index) for index in row.indices],
        "values": [float(value) for value in row.data],
    })

stop_words = sorted(str(word) for word in (vectorizer.get_stop_words() or []))

knowledge = {
    "metadata": {
        "name": "B.E.A. General Knowledge",
        "algorithm": "TF-IDF + Cosine Similarity Retrieval",
        "generative": False,
        "questionCount": int(len(questions)),
        "vocabularySize": int(len(vocabulary)),
        "ngramRange": [1, 2],
    },
    "questions": questions,
    "answers": answers,
    "vocabulary": vocabulary,
    "idf": idf,
    "stopWords": stop_words,
    "vectors": vectors,
}

with OUTPUT_FILE.open("w", encoding="utf-8") as file:
    json.dump(
        knowledge,
        file,
        ensure_ascii=False,
        separators=(",", ":"),
    )

# The Expo app imports a generated TypeScript constant instead of reading a
# training file at runtime. Python is only needed while developing/rebuilding.
typescript_source = (
    "// AUTO-GENERATED by chatbot_training/general_knowledge/build_index.py\n"
    "// Non-generative retrieval index. Do not hand-edit; rebuild it with Python.\n\n"
    "export const GENERAL_KNOWLEDGE_INDEX = "
    + json.dumps(knowledge, ensure_ascii=False, separators=(",", ":"))
    + " as const;\n"
)

TS_OUTPUT_FILE.write_text(typescript_source, encoding="utf-8")

report = {
    "knowledge_entries": int(len(questions)),
    "vocabulary_size": int(len(vocabulary)),
    "matrix_rows": int(matrix.shape[0]),
    "matrix_columns": int(matrix.shape[1]),
    "algorithm": "TF-IDF Retrieval",
    "similarity": "Cosine Similarity",
    "generative_ai": False,
    "typescript_export": str(TS_OUTPUT_FILE),
}

with REPORT_FILE.open("w", encoding="utf-8") as file:
    json.dump(report, file, indent=2)

print()
print("B.E.A. General Knowledge Index built successfully!")
print()
print("Knowledge entries:", len(questions))
print("Vocabulary size:", len(vocabulary))
print("Matrix:", matrix.shape)
print()
print("Created:")
print(OUTPUT_FILE)
print(REPORT_FILE)
print(TS_OUTPUT_FILE)
